### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by yeeha567** [Ogury/ogury-gtm-template#1]
https://github.com/Ogury/ogury-gtm-template/blob/03c90980769fe1a824bb144ef1369422d02564e9/template.tpl#L122

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by anthonyogury** [comment]
Linked to https://github.com/Ogury/ogury-gtm-template/issues/2

**Comment by anthonyogury** [comment]
I have made the changes !
Let me know if it is ok for you.

**Comment by anthonyogury** [comment]
Closing this as I saw it is published. Thanks !
