### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by yeeha567** [Ogury/ogury-gtm-template#2]
https://github.com/Ogury/ogury-gtm-template/blob/03c90980769fe1a824bb144ef1369422d02564e9/template.tpl#L129C6-L129C6

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by anthonyogury** [comment]
Hey @yeeha567,
Thanks for your comment.

Can you elaborate about how you want us to use the mentioned method ? As I understand it, you meant either:
- to use `EncodeUri()` if our parameter is part of the URL path: we don't have the case in the line you mentioned
- to use `EncodeUriComponent()` if our parameter is part of the URL parameter: we have the case and we used it 

Do you mean you want us to use `EncodeUriComponent()` on each of our parameters (such as `event`, `host` and `identifier`) ?

**Comment by anthonyogury** [comment]
I have made the changes.
Let me know if it is ok for you.

**Comment by anthonyogury** [comment]
Closing this as I saw it is published. Thanks !
